# -*- coding: utf-8 -*-
"""Application boundary for strategy candidate generation（R35-A/B）.

这一层只做五件事，而且顺序是固定的：

1. **exact read**：按调用方给出的 exact ``strategy_version`` + ``strategy_checksum``
   读 registry 的 immutable version。没有 head 兜底、没有 ``MAX(version)``、
   没有 "latest"；checksum 不符由 registry 自己 fail closed。
2. **pin**：把读到的定义冻结成 :class:`ParentStrategyPin`。pin 之后，父策略将来
   升级到 v2 也不会改变这个候选绑定的 v1。
3. **declare**：把显式声明组装成 :class:`CandidateSearchSpace`（R35-B）。空间的
   组合基数在这里就能算出来，超限 fail closed。
4. **expand**：把 search space 交给纯生成域
   （``strategy_generator.generate_candidates``）。
5. **append**：写一个 generation batch identity，把候选幂等追加进台账，并把
   本次提案的来源证据（能力身份 + batch）单独追加。

它**不**写 lifecycle、**不**产生 promotion 结论、**不**评估候选、**不**下单、
**不**碰正式账本，也没有 apply/execute 路径：生成出来的东西永远是
``StrategyCandidate``。
"""
from __future__ import annotations

import hashlib
import json
import secrets
import sqlite3

import strategy_candidate as SC
import strategy_candidate_repository as SCRepo
import strategy_candidate_search_space as SS
import strategy_generator as SG
import strategy_registry as SR


class StrategyCandidateUnavailable(ValueError):
    """The requested exact parent version or candidate evidence is unavailable."""


def _canonical(value) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"),
                      ensure_ascii=False, allow_nan=False)


def generation_batch_identity(*, search_space: SS.CandidateSearchSpace,
                              candidate_count: int) -> dict:
    """Freeze one generation request's identity and input fingerprint（§19/§20）.

    Two identities again, same pattern as candidate vs proposal:

    ```text
    batch_id                      → request *event* identity (opaque, per request)
    generation_input_fingerprint  → request *content* identity (canonical)
    ```

    ``generation_input_fingerprint`` 覆盖 exact parent pin、search-space canonical
    fingerprint、generator 能力/契约版本、as-of 与 research provenance —— 因此未来
    可以回答"这一批候选到底是从什么输入生成的"，而不是只留一句"generated by R35-B"。

    ``batch_id`` 是**请求身份**，不是候选身份：同一个 candidate 可以出现在不同
    batch，反过来两个内容完全相同的请求也是两次独立的请求事件（input fingerprint
    相同，batch identity 不同）。batch identity 绝不进 candidate fingerprint。
    """
    if not isinstance(search_space, SS.CandidateSearchSpace):
        raise StrategyCandidateUnavailable("canonical_candidate_search_space_is_required")
    material = {
        "generation_contract_version": SG.GENERATOR_CONTRACT_VERSION,
        "generator_type": search_space.generator_type,
        "generator_version": search_space.generator_version,
        "search_space_contract_version": search_space.search_space_contract_version,
        "search_space_fingerprint": search_space.fingerprint,
        "parent_pin": dict(search_space.parent_pin.identity),
        "asof": search_space.asof,
        "research_provenance": SS._thaw(search_space.research_provenance or {}),
        "hypothesis_id": search_space.hypothesis_id,
        "universe_spec": SS._thaw(search_space.universe_spec),
        "intended_market_regime": search_space.intended_market_regime,
        "constraints": SS._thaw(search_space.constraints),
        "candidate_count": int(candidate_count),
    }
    input_fingerprint = hashlib.sha256(_canonical(material).encode("utf-8")).hexdigest()
    return {
        "batch_id": secrets.token_hex(32),
        "generation_input_fingerprint": input_fingerprint,
        "search_space_fingerprint": search_space.fingerprint,
        "search_space_contract_version": search_space.search_space_contract_version,
        "generator_type": search_space.generator_type,
        "generator_version": search_space.generator_version,
        "generator_contract_version": SG.GENERATOR_CONTRACT_VERSION,
        "parent_strategy_id": search_space.parent_pin.strategy_id,
        "parent_strategy_version": search_space.parent_pin.strategy_version,
        "parent_strategy_checksum": search_space.parent_pin.strategy_checksum,
        "asof": search_space.asof,
        "candidate_count": int(candidate_count),
        "material": material,
    }


def pin_parent_strategy(conn: sqlite3.Connection, *, strategy_id: str,
                        strategy_version: int, strategy_checksum: str,
                        asof: str, research_provenance=None, universe_spec=None,
                        intended_market_regime=None, constraints=None) -> SS.ParentStrategyPin:
    """Read one **exact** immutable strategy version and freeze it as a pin.

    ``strategy_registry.get_version`` raises when the exact version exists but its
    checksum differs, and returns ``None`` when the version does not exist. Both
    mean the same thing here: we cannot establish the parent identity, so we fail
    closed instead of falling back to the current head.
    """
    if not isinstance(strategy_id, str) or not strategy_id.strip():
        raise StrategyCandidateUnavailable("explicit_parent_strategy_id_required")
    if isinstance(strategy_version, bool) or not isinstance(strategy_version, int) \
            or strategy_version < 1:
        raise StrategyCandidateUnavailable("explicit_parent_strategy_version_required")
    if not isinstance(strategy_checksum, str) or not SC._SHA256.fullmatch(strategy_checksum):
        raise StrategyCandidateUnavailable("explicit_parent_strategy_checksum_required")
    try:
        record = SR.get_version(str(strategy_id).strip(), int(strategy_version),
                                checksum=str(strategy_checksum), conn=conn)
    except (ValueError, sqlite3.Error) as exc:
        raise StrategyCandidateUnavailable("exact_parent_strategy_version_unavailable") from exc
    if record is None:
        raise StrategyCandidateUnavailable("exact_parent_strategy_version_unavailable")
    definition = dict(record.definition)
    dsl_ast = definition.get("dsl_ast")
    if dsl_ast is None:
        # 没有声明式 DSL 的父策略（native built-in）不能作为受约束生成的基础：
        # 生成域只接受 bounded DSL，绝不为 native 实现发明第二套表达式语言。
        raise StrategyCandidateUnavailable("parent_strategy_has_no_declarative_dsl")
    metadata = dict(definition.get("metadata") or {})
    return SS.ParentStrategyPin(
        strategy_id=str(record.strategy_id), strategy_version=int(record.version),
        strategy_checksum=str(record.checksum), dsl_ast=dsl_ast, asof=asof,
        research_provenance=(research_provenance
                             if research_provenance is not None
                             else metadata.get("research_provenance")),
        universe_spec=(universe_spec if universe_spec is not None
                       else metadata.get("universe_spec")),
        intended_market_regime=(intended_market_regime
                                if intended_market_regime is not None
                                else metadata.get("intended_market_regime")),
        # 调用方没给约束时**继承父策略那一版自己的约束**，而不是变成空集：
        # 空集不是"无约束"，而是"把父策略的仓位/敞口/权重上限悄悄丢掉"，
        # 那会让下游实验读到一份并非父策略语义的候选。
        constraints=(constraints if constraints is not None
                     else metadata.get("constraints")),
        exit_spec=metadata.get("exit_spec"),
        factor_spec=metadata.get("factor_spec"),
    )


def build_search_space(pin: SS.ParentStrategyPin, *, generator_type: str,
                       generator_version: str, asof: str, universe_spec,
                       intended_market_regime: str, parameter_variants=None,
                       factor_slot=None, entry_slot=None, exit_slot=None,
                       combination_policy: str = SS.CARTESIAN_COMBINATION,
                       max_candidates: int = SS.MAX_CANDIDATES_PER_GENERATION_REQUEST,
                       evidence_count: int | None = None,
                       hypothesis_id: str | None = None, research_provenance=None,
                       random_seed: int | None = None, model_identity=None,
                       constraints=None) -> SS.CandidateSearchSpace:
    """Assemble one explicit search space from already-captured facts.

    只做组装与显式缺省：能力身份来自调用方，universe / regime 来自 pin 或显式
    override，constraints 默认继承 exact pinned parent 且只能收紧。没有任何
    "读一下当前状态"的路径。
    """
    if pin.universe_spec is None and universe_spec is None:
        raise StrategyCandidateUnavailable("explicit_universe_spec_required")
    if pin.intended_market_regime is None and not str(intended_market_regime or "").strip():
        raise StrategyCandidateUnavailable("explicit_intended_market_regime_required")
    slots = {}
    for role, declared in (("factor", factor_slot), ("entry", entry_slot),
                           ("exit", exit_slot)):
        slots[role] = ({"kind": SS.INHERIT_PARENT} if declared is None else declared)
    return SS.CandidateSearchSpace(
        parent_pin=pin, asof=asof,
        universe_spec=(universe_spec if universe_spec is not None else pin.universe_spec),
        intended_market_regime=(intended_market_regime
                                or pin.intended_market_regime),
        generator_type=generator_type, generator_version=generator_version,
        parameter_variants=parameter_variants or {},
        factor_slot=slots["factor"], entry_slot=slots["entry"], exit_slot=slots["exit"],
        combination_policy=combination_policy, max_candidates=max_candidates,
        evidence_count=evidence_count, hypothesis_id=hypothesis_id,
        research_provenance=(research_provenance if research_provenance is not None
                             else pin.research_provenance),
        random_seed=random_seed, model_identity=model_identity, constraints=constraints)


def generate_and_record_candidates(
    conn: sqlite3.Connection, *, strategy_id: str, strategy_version: int,
    strategy_checksum: str, asof: str, universe_spec, intended_market_regime: str,
    generator_type: str = SG.PARAMETER_VARIANT_GENERATOR,
    generator_version: str = SG.PARAMETER_VARIANT_VERSION,
    parameter_variants=None, parameter_adjustments=None,
    factor_slot=None, entry_slot=None, exit_slot=None,
    combination_policy: str = SS.CARTESIAN_COMBINATION,
    max_candidates: int = SS.MAX_CANDIDATES_PER_GENERATION_REQUEST,
    evidence_count: int | None = None, hypothesis_id: str | None = None,
    research_provenance=None, random_seed: int | None = None,
    model_identity=None, constraints=None, created_at: str | None = None,
) -> dict:
    """Expand one explicit bounded search space and record the batch + proposals.

    The caller owns the SQLite connection and transaction. Returns a projection of
    what was produced plus the batch/proposal identities, and nothing about strategy
    quality: this service has no opinion on whether a candidate is any good.

    ``parameter_adjustments`` 是 R35-A 的入口名，等价于 ``parameter_variants``；
    两者同时给出即拒绝，避免同一件事有两个真相来源。
    """
    if parameter_variants is not None and parameter_adjustments is not None:
        raise StrategyCandidateUnavailable("ambiguous_parameter_declaration")
    variants = parameter_variants if parameter_variants is not None else parameter_adjustments
    pin = pin_parent_strategy(
        conn, strategy_id=strategy_id, strategy_version=strategy_version,
        strategy_checksum=strategy_checksum, asof=asof,
        research_provenance=research_provenance, universe_spec=universe_spec,
        intended_market_regime=intended_market_regime, constraints=None)
    search_space = build_search_space(
        pin, generator_type=generator_type, generator_version=generator_version,
        asof=asof, universe_spec=universe_spec,
        intended_market_regime=intended_market_regime,
        parameter_variants=variants, factor_slot=factor_slot, entry_slot=entry_slot,
        exit_slot=exit_slot, combination_policy=combination_policy,
        max_candidates=max_candidates, evidence_count=evidence_count,
        hypothesis_id=hypothesis_id, research_provenance=research_provenance,
        random_seed=random_seed, model_identity=model_identity, constraints=constraints)
    candidates = SG.generate_candidates(search_space)
    batch = generation_batch_identity(search_space=search_space,
                                      candidate_count=len(candidates))
    SCRepo.record_generation_batch(conn, batch=batch, created_at=created_at)
    # proposal 事件的 provenance 全部取自 **search space / batch 的显式事实**，
    # 绝不再从 candidate 反推：candidate 是内容身份，不携带 provenance。
    provenance = {
        "hypothesis_id": search_space.hypothesis_id,
        "research_provenance": SS._thaw(search_space.research_provenance or {}),
        "random_seed": search_space.random_seed,
        "model_identity": SS._thaw(search_space.model_identity or {}),
    }
    recorded = []
    for candidate in candidates:
        SCRepo.append_candidate(conn, candidate, created_at=created_at)
        SCRepo.record_proposal(
            conn, candidate,
            input_fingerprint=batch["generation_input_fingerprint"],
            generator_type=search_space.generator_type,
            generator_version=search_space.generator_version,
            generator_contract_version=SG.GENERATOR_CONTRACT_VERSION,
            generation_batch_id=batch["batch_id"], **provenance,
            created_at=created_at)
        recorded.append(candidate.projection())
    return {
        "authority": "strategy_candidate_generation",
        "generator_type": search_space.generator_type,
        "generator_version": search_space.generator_version,
        "generator_contract_version": SG.GENERATOR_CONTRACT_VERSION,
        "search_space_contract_version": search_space.search_space_contract_version,
        "search_space_fingerprint": search_space.fingerprint,
        "input_fingerprint": batch["generation_input_fingerprint"],
        "generation_batch_id": batch["batch_id"],
        "generation_input_fingerprint": batch["generation_input_fingerprint"],
        "parent_strategy_pin": pin.identity,
        "asof": pin.asof,
        "candidate_count": len(recorded),
        "candidate_ids": [item["candidate_id"] for item in recorded],
        "candidates": recorded,
    }


def get_generation_batch(conn: sqlite3.Connection, batch_id: str) -> dict:
    """Read exactly one generation batch by id; never "the latest one"."""
    try:
        batch = SCRepo.get_generation_batch(conn, str(batch_id or ""))
    except (SCRepo.StrategyCandidateRepositoryError, sqlite3.Error) as exc:
        raise StrategyCandidateUnavailable("candidate_evidence_unavailable") from exc
    if batch is None:
        raise StrategyCandidateUnavailable("generation_batch_not_found")
    proposals = SCRepo.list_batch_proposals(conn, str(batch_id))
    return {
        "authority": "read_only_exact_generation_batch_projection",
        "generation_batch": batch,
        "proposals": list(proposals),
    }


def get_candidate(conn: sqlite3.Connection, candidate_id: str) -> dict:
    """Read exactly one candidate by id; never "the latest one"."""
    try:
        candidate = SCRepo.get_candidate(conn, str(candidate_id or ""))
    except (SCRepo.StrategyCandidateRepositoryError, sqlite3.Error) as exc:
        raise StrategyCandidateUnavailable("candidate_evidence_unavailable") from exc
    if candidate is None:
        raise StrategyCandidateUnavailable("strategy_candidate_not_found")
    try:
        proposals = SCRepo.list_proposals(conn, candidate.candidate_id)
    except (SCRepo.StrategyCandidateRepositoryError, sqlite3.Error) as exc:
        raise StrategyCandidateUnavailable("candidate_evidence_unavailable") from exc
    projection = candidate.projection()
    return {
        "authority": "read_only_exact_candidate_projection",
        "candidate": projection,
        # 持久化元数据（created_at）不属于 candidate identity，因此单独作为台账
        # 事实发布：前端要显示"什么时候记的"时读它，而不是读指纹材料。
        "persistence": SCRepo.get_candidate_persistence(conn, candidate.candidate_id),
        # 只读事实：candidate 台账里没有评估结论，因此状态就是 CANDIDATE 本身。
        "status": "CANDIDATE",
        "parent_strategy_pin": candidate.identity(),
        "proposals": list(proposals),
        # 前端**不得**自行判断候选是否优秀 / 能否晋级 / 是否允许进 Shadow；
        # 这些结论以后由 backend contract 返回，R35-A 明确不发布它们。
        "evaluation": None,
        "promotion": None,
    }


def list_candidates_for_parent(conn: sqlite3.Connection, *, strategy_id: str,
                               strategy_version: int,
                               strategy_checksum: str) -> dict:
    """List candidates pinned to one exact parent version (append order)."""
    rows = conn.execute(
        """SELECT candidate_id FROM strategy_candidates
            WHERE parent_strategy_id=? AND parent_strategy_version=?
              AND parent_strategy_checksum=?
            ORDER BY created_at,candidate_id""",
        (str(strategy_id), int(strategy_version), str(strategy_checksum)),
    ).fetchall()
    items = []
    batch_ids: list[str] = []
    for row in rows:
        candidate_id = str(row[0])
        read = get_candidate(conn, candidate_id)
        evidence = _proposal_evidence_refs(read["proposals"])
        items.append({"candidate": read["candidate"], "persistence": read["persistence"],
                      # R35-B：generator 能力 / batch 是**提案事件**的 provenance，
                      # 不是候选行的事实。这里发布**全部**证据引用而不是"最近一条"：
                      # proposal id 是随机 opaque id，同 timestamp 下 `proposals[-1]`
                      # 只是"随机 id 排序靠后"，不是可靠的 latest，压成 latest 就是
                      # 在 append-only 历史上重新投影出一个隐含的 current 指针。
                      "proposal_evidence": evidence})
        for batch_id in evidence["generation_batch_ids"]:
            if batch_id and batch_id not in batch_ids:
                batch_ids.append(batch_id)
    return {
        "authority": "read_only_exact_parent_candidates",
        "parent_strategy_pin": {"strategy_id": str(strategy_id),
                                "strategy_version": int(strategy_version),
                                "strategy_checksum": str(strategy_checksum)},
        "items": items,
        # 只按**显式 batch id**读取（绝不查"最新一批"）；每个 batch 只出现一次。
        # 要看某个 batch 的完整输入，调用方直接用
        # GET /api/strategies/{id}/candidate-generations/{batch_id}。
        "generation_batches": [get_generation_batch(conn, batch_id)["generation_batch"]
                               for batch_id in batch_ids],
    }


def _proposal_evidence_refs(proposals) -> dict:
    """Every proposal event of one candidate, as unordered explicit references.

    这里**不**做"最近一条"投影：``proposal_id`` 是随机 opaque id，两条事件可以合法
    拥有完全相同的 ``created_at``，因此 ``proposals[-1]`` 只是一个稳定但语义错误的
    "latest"。append-only 历史要么完整给出，要么用显式 id 单独取；重新投影出一个
    隐含 current/latest 指针会与本层"没有 latest/current 读路径"的契约冲突。
    """
    refs = [{"proposal_id": item.get("proposal_id"),
             "generation_batch_id": item.get("generation_batch_id"),
             "created_at": item.get("created_at")}
            for item in proposals]
    return {
        "proposal_count": len(refs),
        "proposals": refs,
        "generation_batch_ids": [item["generation_batch_id"] for item in refs],
    }


def _with_paper_connection(work, *, immediate: bool = False):
    """Connection ownership for the HTTP entry points only.

    The core functions above stay connection-explicit so they can be tested and
    composed; only these public entry points open a connection (same pattern as
    the other evidence owners in this repository).
    """
    import paper_trading as PT
    PT.init_db()
    with PT._db(immediate=immediate) as conn:
        return work(conn)


def capture_strategy_candidates(strategy_id: str, **kwargs) -> dict:
    """Generate candidates from one exact pinned parent and append them."""
    def _work(conn):
        return generate_and_record_candidates(conn, strategy_id=strategy_id, **kwargs)
    return _with_paper_connection(_work, immediate=True)


def read_strategy_candidate(candidate_id: str) -> dict:
    """Read exactly one candidate by id; never "the latest one"."""
    def _work(conn):
        return get_candidate(conn, candidate_id)
    return _with_paper_connection(_work)


def read_parent_candidates(strategy_id: str, *, strategy_version: int,
                           strategy_checksum: str) -> dict:
    def _work(conn):
        return list_candidates_for_parent(
            conn, strategy_id=strategy_id, strategy_version=strategy_version,
            strategy_checksum=strategy_checksum)
    return _with_paper_connection(_work)


def read_generation_batch(batch_id: str) -> dict:
    def _work(conn):
        return get_generation_batch(conn, batch_id)
    return _with_paper_connection(_work)


__all__ = ["StrategyCandidateUnavailable", "build_search_space",
           "capture_strategy_candidates", "generate_and_record_candidates",
           "generation_batch_identity", "get_candidate", "get_generation_batch",
           "list_candidates_for_parent", "pin_parent_strategy",
           "read_generation_batch", "read_parent_candidates",
           "read_strategy_candidate"]
