/* PR-55：inline 事件处理器的**兼容桥**。
   index.html 与各模块生成的 HTML 里大量使用 onclick="fn(...)"；
   模块化后这些名字不再自动是全局，这里逐个显式挂到 window 上。
   新增 inline handler 时，把被调用的函数加到对应 import 与赋值列表。
   由 backend/test_frontend_module_contract.py 校验覆盖率。 */

import { adaptiveEsc } from "./core/format.js";
import { activatePage, refreshApp, showPaperWorkspace, toggleDark } from "./core/navigation.js";
import { applyAdaptiveRiskCandidate, applyAdaptiveSelectionCandidate, approveAdaptiveNeural, loadAdaptive, loadEvolutionStatus, recordAdaptiveFeedback, refreshAdaptiveTimelineNow, retryAdaptiveAiWindow, rollbackAdaptiveRebalance, rollbackAdaptiveRisk, rollbackAdaptiveSelection, runAdaptive, runAdaptiveAdvisor, runAdaptiveAiTuning, runAdaptiveResearchSuite, runAdaptiveResearchTask, runDualAiTuning, runNewsLearning, setAdaptiveSection, switchToAdaptiveAI, testModlensRead, triggerEvolution } from "./features/adaptive.js";
import { loadPaperExecution, verifyExecutionOrder } from "./features/execution.js";
import { backfillPaperResearch, cancelPaperOrder, clearPaperOrderDate, clearPaperOrderPreview, filterPaperHistoryRows, loadPaperStockHistory, pausePaper, preparePaperSell, previewPaperOrder, refreshPaperResearchValidation, resetPaper, resumePaper, runPaperNow, selectPaperHistoryQuick, setPaperOrderSide, setPaperTerminalFilter, showPaperStockHistory, startPaper, submitPaperOrder, syncPaperCapitalHint, togglePaperLimitPrice } from "./features/paper.js";
import { applyPaperRiskAuditFilter, loadPaperRisk, refreshPaperRisk } from "./features/risk.js";
import { cancelManualDataUpdate, choosePaperStrategy, chooseStrategy, filterSelectionEvaluationRows, loadDataValidity, loadPaperSelection, loadSelectionEvaluation, refreshSelectionEvaluation, runPaperSelection, showSelectionValidation, startFactorIncrementalUpdate, startInit, startManualDataUpdate, trackRemove } from "./features/selection.js";
import { refreshSettingsKeyForm, resetSettingsSection, saveSettingsKey, saveSettingsSection, setSettingsSection } from "./features/settings.js";
import { loadStrategyWorkbench, openInStrategyWorkbench, wbAddCondition, wbBackToList, wbCloneFirstBuiltin, wbCloneStrategy, wbDeleteDraft, wbFormatDsl, wbFromConditionsToDsl, wbNewStrategy, wbOpenDetail, wbOpenEditor, wbPreviewDraft, wbRemoveCondition, wbRenderList, wbResetFilters, wbSaveDraft, wbSetMode, wbSetOriginFilter, wbSetStatusFilter, wbTransition, wbValidateAndMark, wbValidateDraft } from "./features/strategies.js";

window.activatePage = activatePage;
window.adaptiveEsc = adaptiveEsc;
window.applyAdaptiveRiskCandidate = applyAdaptiveRiskCandidate;
window.applyAdaptiveSelectionCandidate = applyAdaptiveSelectionCandidate;
window.applyPaperRiskAuditFilter = applyPaperRiskAuditFilter;
window.approveAdaptiveNeural = approveAdaptiveNeural;
window.backfillPaperResearch = backfillPaperResearch;
window.cancelManualDataUpdate = cancelManualDataUpdate;
window.cancelPaperOrder = cancelPaperOrder;
window.choosePaperStrategy = choosePaperStrategy;
window.chooseStrategy = chooseStrategy;
window.clearPaperOrderDate = clearPaperOrderDate;
window.clearPaperOrderPreview = clearPaperOrderPreview;
window.filterPaperHistoryRows = filterPaperHistoryRows;
window.filterSelectionEvaluationRows = filterSelectionEvaluationRows;
window.loadAdaptive = loadAdaptive;
window.loadDataValidity = loadDataValidity;
window.loadEvolutionStatus = loadEvolutionStatus;
window.loadPaperExecution = loadPaperExecution;
window.loadPaperRisk = loadPaperRisk;
window.loadPaperSelection = loadPaperSelection;
window.loadPaperStockHistory = loadPaperStockHistory;
window.loadSelectionEvaluation = loadSelectionEvaluation;
window.loadStrategyWorkbench = loadStrategyWorkbench;
window.openInStrategyWorkbench = openInStrategyWorkbench;
window.pausePaper = pausePaper;
window.preparePaperSell = preparePaperSell;
window.previewPaperOrder = previewPaperOrder;
window.recordAdaptiveFeedback = recordAdaptiveFeedback;
window.refreshAdaptiveTimelineNow = refreshAdaptiveTimelineNow;
window.refreshApp = refreshApp;
window.refreshPaperResearchValidation = refreshPaperResearchValidation;
window.refreshPaperRisk = refreshPaperRisk;
window.refreshSelectionEvaluation = refreshSelectionEvaluation;
window.refreshSettingsKeyForm = refreshSettingsKeyForm;
window.resetPaper = resetPaper;
window.resetSettingsSection = resetSettingsSection;
window.resumePaper = resumePaper;
window.retryAdaptiveAiWindow = retryAdaptiveAiWindow;
window.rollbackAdaptiveRebalance = rollbackAdaptiveRebalance;
window.rollbackAdaptiveRisk = rollbackAdaptiveRisk;
window.rollbackAdaptiveSelection = rollbackAdaptiveSelection;
window.runAdaptive = runAdaptive;
window.runAdaptiveAdvisor = runAdaptiveAdvisor;
window.runAdaptiveAiTuning = runAdaptiveAiTuning;
window.runAdaptiveResearchSuite = runAdaptiveResearchSuite;
window.runAdaptiveResearchTask = runAdaptiveResearchTask;
window.runDualAiTuning = runDualAiTuning;
window.runNewsLearning = runNewsLearning;
window.runPaperNow = runPaperNow;
window.runPaperSelection = runPaperSelection;
window.saveSettingsKey = saveSettingsKey;
window.saveSettingsSection = saveSettingsSection;
window.selectPaperHistoryQuick = selectPaperHistoryQuick;
window.setAdaptiveSection = setAdaptiveSection;
window.setPaperOrderSide = setPaperOrderSide;
window.setPaperTerminalFilter = setPaperTerminalFilter;
window.setSettingsSection = setSettingsSection;
window.showPaperStockHistory = showPaperStockHistory;
window.showPaperWorkspace = showPaperWorkspace;
window.showSelectionValidation = showSelectionValidation;
window.startFactorIncrementalUpdate = startFactorIncrementalUpdate;
window.startInit = startInit;
window.startManualDataUpdate = startManualDataUpdate;
window.startPaper = startPaper;
window.submitPaperOrder = submitPaperOrder;
window.switchToAdaptiveAI = switchToAdaptiveAI;
window.syncPaperCapitalHint = syncPaperCapitalHint;
window.testModlensRead = testModlensRead;
window.toggleDark = toggleDark;
window.togglePaperLimitPrice = togglePaperLimitPrice;
window.trackRemove = trackRemove;
window.triggerEvolution = triggerEvolution;
window.verifyExecutionOrder = verifyExecutionOrder;
window.wbAddCondition = wbAddCondition;
window.wbBackToList = wbBackToList;
window.wbCloneStrategy = wbCloneStrategy;
window.wbCloneFirstBuiltin = wbCloneFirstBuiltin;
window.wbDeleteDraft = wbDeleteDraft;
window.wbFormatDsl = wbFormatDsl;
window.wbFromConditionsToDsl = wbFromConditionsToDsl;
window.wbNewStrategy = wbNewStrategy;
window.wbOpenDetail = wbOpenDetail;
window.wbOpenEditor = wbOpenEditor;
window.wbPreviewDraft = wbPreviewDraft;
window.wbRemoveCondition = wbRemoveCondition;
window.wbRenderList = wbRenderList;
window.wbResetFilters = wbResetFilters;
window.wbSaveDraft = wbSaveDraft;
window.wbSetMode = wbSetMode;
window.wbSetOriginFilter = wbSetOriginFilter;
window.wbSetStatusFilter = wbSetStatusFilter;
window.wbTransition = wbTransition;
window.wbValidateAndMark = wbValidateAndMark;
window.wbValidateDraft = wbValidateDraft;
