from pathlib import Path

strategies = Path("backend/strategies.py")
text = strategies.read_text(encoding="utf-8")
old = '''    for factor in ("mom_short", "mom", "volsurge", "rsi"):\n        table[f"{factor}_evidence_quality"] = price_quality.where(\n            table[factor].notna(), 0.0\n        )\n    table["value_evidence_quality"] = table["value"].notna().astype(float)\n    table["quality_evidence_quality"] = table["quality"].notna().astype(float)\n'''
new = '''    table["mom_short_evidence_quality"] = price_quality.where(mom5_z.notna(), 0.0)\n    table["mom_evidence_quality"] = price_quality * (\n        mom20_z.notna().astype(float) * 0.6 + mom60_z.notna().astype(float) * 0.4\n    )\n    table["volsurge_evidence_quality"] = price_quality.where(\n        table["volsurge"].notna(), 0.0\n    )\n    table["rsi_evidence_quality"] = price_quality.where(table["rsi"].notna(), 0.0)\n    table["value_evidence_quality"] = (\n        pe_z.notna().astype(float) * 0.5 + pb_z.notna().astype(float) * 0.5\n    )\n    table["quality_evidence_quality"] = (\n        roe_z.notna().astype(float) * 0.5\n        + profit_z.notna().astype(float) * 0.25\n        + revenue_z.notna().astype(float) * 0.25\n    )\n'''
assert old in text, "strategies nested-quality target not found"
strategies.write_text(text.replace(old, new, 1), encoding="utf-8")

tests = Path("backend/test_factor_calibration_v2.py")
test_text = tests.read_text(encoding="utf-8")
anchor = '''    def test_price_quality_propagates_without_mutating_factor_alpha(self):\n        price, fund = self._frames()\n        table = S.build_factor_table(price, fund)\n        code = price.index[1]\n        self.assertEqual(float(table.loc[code, "mom_short_evidence_quality"]), 0.7)\n        self.assertEqual(float(table.loc[code, "mom_evidence_quality"]), 0.7)\n        self.assertEqual(table.attrs["factor_calibration_version"], FC.CALIBRATION_VERSION)\n\n\nclass RuntimeCalibrationTests(unittest.TestCase):\n'''
replacement = '''    def test_price_quality_propagates_without_mutating_factor_alpha(self):\n        price, fund = self._frames()\n        table = S.build_factor_table(price, fund)\n        code = price.index[1]\n        self.assertEqual(float(table.loc[code, "mom_short_evidence_quality"]), 0.7)\n        self.assertEqual(float(table.loc[code, "mom_evidence_quality"]), 0.7)\n        self.assertEqual(table.attrs["factor_calibration_version"], FC.CALIBRATION_VERSION)\n\n    def test_nested_composite_quality_tracks_component_coverage(self):\n        price, fund = self._frames()\n        code = price.index[0]\n        fund.loc[code, "pb"] = np.nan\n        fund.loc[code, "profit_yoy"] = np.nan\n        fund.loc[code, "rev_yoy"] = np.nan\n        price.loc[code, "mom60"] = np.nan\n        table = S.build_factor_table(price, fund)\n        self.assertAlmostEqual(float(table.loc[code, "value_evidence_quality"]), 0.5)\n        self.assertAlmostEqual(float(table.loc[code, "quality_evidence_quality"]), 0.5)\n        self.assertAlmostEqual(float(table.loc[code, "mom_evidence_quality"]), 0.6)\n        self.assertTrue(pd.notna(table.loc[code, "value"]))\n        self.assertTrue(pd.notna(table.loc[code, "quality"]))\n        self.assertTrue(pd.notna(table.loc[code, "mom"]))\n\n\nclass RuntimeCalibrationTests(unittest.TestCase):\n'''
assert anchor in test_text, "test insertion target not found"
tests.write_text(test_text.replace(anchor, replacement, 1), encoding="utf-8")
